### ISSUE TITLE
Added the paper to "DataAug4Code" repo

### ISSUE THREAD

**Issue by terryyz** [Veronicium/CMTrans#1]
Dear Yiqing,

Just a note that I've added your paper to [DataAug4Code](https://github.com/terryyz/DataAug4Code) Survey repo. I'll also update your paper in our [paper](https://arxiv.org/abs/2305.19915) 😃 

Cheers,
Terry

**Comment by yiqingxyq** [comment]
Thanks, Terry! It's a good survey paper :)
